### ISSUE TITLE
frontend build error

### ISSUE THREAD

**Issue by flashlab-bio** [rnons/ted2srt#2]
Hi, rnons. I follow to instruction to build the front end. When excute `yarn build`, I got some errors
```
ERROR in ./src/HomePage.ts
Module not found: Error: Can't resolve 'Home' in '/home/ubuntu/ted2srt/frontend/src'
resolve 'Home' in '/home/ubuntu/ted2srt/frontend/src'
  Parsed request is a module
  using description file: /home/ubuntu/ted2srt/frontend/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/ubuntu/ted2srt/frontend/src/node_modules doesn't exist or is not a directory
      /home/ubuntu/ted2srt/frontend/src/dce-output doesn't exist or is not a directory
      /home/ubuntu/ted2srt/frontend/src/src doesn't exist or is not a directory
      /home/ubuntu/ted2srt/frontend/dce-output doesn't exist or is not a directory
      /home/ubuntu/ted2srt/node_modules doesn't exist or is not a directory
      /home/ubuntu/ted2srt/dce-output doesn't exist or is not a directory
      /home/ubuntu/ted2srt/src doesn't exist or is not a directory
      /home/ubuntu/node_modules doesn't exist or is not a directory
      /home/ubuntu/dce-output doesn't exist or is not a directory
      /home/ubuntu/src doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /home/dce-output doesn't exist or is not a directory
      /home/src doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      /dce-output doesn't exist or is not a directory
      /src doesn't exist or is not a directory
      looking for modules in /home/ubuntu/ted2srt/frontend/node_modules
        using description file: /home/ubuntu/ted2srt/frontend/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /home/ubuntu/ted2srt/frontend/src
        using description file: /home/ubuntu/ted2srt/frontend/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/ubuntu/ted2srt/frontend/package.json (relative path: ./node_modules/Home)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/ubuntu/ted2srt/frontend/package.json (relative path: ./src/Home)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/ubuntu/ted2srt/frontend/node_modules/Home doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/ubuntu/ted2srt/frontend/src/Home is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/ubuntu/ted2srt/frontend/node_modules/Home.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/ubuntu/ted2srt/frontend/src/Home.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/ubuntu/ted2srt/frontend/node_modules/Home.ts doesn't exist
              /home/ubuntu/ted2srt/frontend/src/Home.ts doesn't exist
            as directory
              /home/ubuntu/ted2srt/frontend/node_modules/Home doesn't exist
            as directory
              existing directory
                using path: /home/ubuntu/ted2srt/frontend/src/Home/index
                  using description file: /home/ubuntu/ted2srt/frontend/package.json (relative path: ./src/Home/index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      /home/ubuntu/ted2srt/frontend/src/Home/index doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      /home/ubuntu/ted2srt/frontend/src/Home/index.js doesn't exist
                    .ts
                      Field 'browser' doesn't contain a valid alias configuration
                      /home/ubuntu/ted2srt/frontend/src/Home/index.ts doesn't exist
```

Can you give some tips how to resolve it. Thank you ;)

**Comment by rnons** [comment]
Hi, from the error message `src/node_modules doesn't exist or is not a directory`, seems you forgot to run `yarn`?

Also, I pushed a commit just now, please run `git pull` before `yarn`. And take a look at the updated README.
Let me know if there are other problems.

**Comment by rnons** [comment]
For the backend, you need to init tables in database, one way is to run
 `psql -U postgres -d ted2srt < backend/sql/latest.sql`.

The other way is un-comment all commented lines in `backend/app/main.hs` before `stack build`, and after `stack exec`, comment those lines again.

Sorry it's a bit mess here.

**Comment by flashlab-bio** [comment]
@rnons Thank you for your reply. I did the latest patch and run the protocol again. still got stuck with `yarn build`. I did't see `node_modules` created after `yarn`, should it be a problem. Or should I run `yarn` under src folder 😕

**Comment by rnons** [comment]
You should run `yarn` inside `frontend`, that's what `cd frontend` do in the README
```
cd frontend
yarn
pulp -w build
yarn start
```

It is a problem if there is no `node_modules`. Is there any output after `yarn`?

**Comment by rnons** [comment]
Oh, I misread your original error message, `frontend/node_modules` should exist after `yarn`, and you should run `yarn build` under `frontend` as well.

**Comment by rnons** [comment]
I just realized you need to install [zephyr](https://github.com/coot/zephyr/releases) to run `yarn build`, just download it and copy the bin to any of you `$PATH`

**Comment by flashlab-bio** [comment]
@rnons now the server works fine now✌️ While the homepage shows empty content, I guess the entry came from the feedburner fetched by the server itself. If so, can I switch to another rss source like [the official one](https://pa.tedcdn.com/feeds/talks.rss) because of the source's accessibility. There structure looks like the same.

**Comment by rnons** [comment]
Cool. You can search something to fill some data to database, or run `stack exec fetch` to fetch from feedburner.
I think the feedburner link is also official, I found it from official website long time ago. If `stack exec fetch` work with the new feed link, I'm fine with changing.

**Comment by flashlab-bio** [comment]
So it means search action can trigger fetching from the remote server 🤔 can I track the process or locate the corresponding source code. thank you for your great work 🤝

**Comment by rnons** [comment]
> search action can trigger fetching from the remote server

Sorry, I forgot this is no longer true, see [this commit](https://github.com/rnons/ted2srt/commit/8615b98e827167d958bc74f5a50e2d019a77c989).

Previously, TED provides [open api](http://developer.ted.com/), but it was shut down. Aside from `stack exec fetch`, you can change any talk page url, e.g. `https://www.ted.com/talks/juan_enriquez_what_will_humans_look_like_in_100_years` to `http://localhost:8080/talks/juan_enriquez_what_will_humans_look_like_in_100_years` to fetch that talk

**Comment by flashlab-bio** [comment]
I understand that, also, if I modified the fetching address from source code, how to apply the change to the server? Simply change `app/fetch.hs` is not work.

**Comment by rnons** [comment]
You need to run `stack build` again to generate new binary of fetch. Then
stack exec

2018年12月12日(水) 23:00、Zheng Juefei さん（notifications@github.com）のメッセージ:
