### ISSUE TITLE
"Something went wrong" issue

### ISSUE THREAD

**Issue by ekincis** [rnons/ted2srt#22]
When I click on the most of the videos, "something went wrong" has been appearing on my screen for the last 2 days. It would be perfect if there is a way to solve this problem. Thanks so much in advance.

**Comment by rnons** [comment]
Thanks for reporting. Sorry I don't have time to fix this.

**Comment by BayarBH** [comment]
> 
Cannot open website

**Comment by rnons** [comment]
Please try https://ted2sub.org
