### ISSUE TITLE
subtitle merge issue

### ISSUE THREAD

**Issue by flashlab-bio** [rnons/ted2srt#3]
Dear rnons,

I notice the merging strategy of subtitles may cause strange behaviour if  two language script is not synchronization. For example, [this pages](https://ted2srt.org/talks/larry_smith_why_you_will_fail_to_have_a_great_career),  Single language subtitle works fine. But if I choose two language(en & zh-cn), the english text is not proper match the timeline. I notice in the srt file, timestamp have two lines. So can the merging procedure intelligently process the asynchronization issue or generate two vtt in the subtitle section.
Same problem appears in the main content, if two language don't match, the longer one will be cut.

I'm not sure if I have make myself clear. Thanks~

**Comment by rnons** [comment]
You're right, it is possible to use timestamp in srt to handle it better. But I don't have much interest in doing that, as it will make things a bit more complicated. I guess this problem mostly happens on very old talks. If you want to fix it, PR welcome. :smiley:

**Comment by flashlab-bio** [comment]
I will have a try, thanks a lot ；）
